# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    restart: always
    environment:
      RANDOM_ROOT_PASSWORD: yes
      POSTGRES_DATABASE: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef